CREATE TABLE [APPLICATION_REGISTER] (
    [APPLICATION_REGISTER_ID] bigint NOT NULL IDENTITY,
    [APPLICATION_KEY] nvarchar(max) NULL,
    [SHARED_SECRET] nvarchar(max) NULL,
    CONSTRAINT [PK_APPLICATION_REGISTER] PRIMARY KEY ([APPLICATION_REGISTER_ID])
);
GO


CREATE TABLE [ENVIRONMENT] (
    [ENVIRONMENT_ID] uniqueidentifier NOT NULL,
    [AUTHENTICATION_METHOD] nvarchar(max) NULL,
    [CONSUMER_NAME] nvarchar(max) NULL,
    [INSTANCE_ID] nvarchar(max) NULL,
    [SESSION_TOKEN] nvarchar(max) NULL,
    [SOLUTION_ID] nvarchar(max) NULL,
    [TYPE] nvarchar(max) NULL,
    [USER_TOKEN] nvarchar(max) NULL,
    CONSTRAINT [PK_ENVIRONMENT] PRIMARY KEY ([ENVIRONMENT_ID])
);
GO


CREATE TABLE [Sessions] (
    [Id] uniqueidentifier NOT NULL,
    [ApplicationKey] nvarchar(max) NOT NULL,
    [EnvironmentUrl] nvarchar(max) NOT NULL,
    [InstanceId] nvarchar(max) NULL,
    [QueueId] nvarchar(max) NULL,
    [SessionToken] nvarchar(max) NOT NULL,
    [SolutionId] nvarchar(max) NULL,
    [SubscriptionId] nvarchar(max) NULL,
    [UserToken] nvarchar(max) NULL,
    CONSTRAINT [PK_Sessions] PRIMARY KEY ([Id])
);
GO


CREATE TABLE [ENVIRONMENT_REGISTER] (
    [ENVIRONMENT_REGISTER_ID] bigint NOT NULL IDENTITY,
    [APPLICATION_KEY] nvarchar(max) NULL,
    [INSTANCE_ID] nvarchar(max) NULL,
    [SOLUTION_ID] nvarchar(max) NULL,
    [USER_TOKEN] nvarchar(max) NULL,
    [APPLICATION_REGISTER_ID] bigint NULL,
    CONSTRAINT [PK_ENVIRONMENT_REGISTER] PRIMARY KEY ([ENVIRONMENT_REGISTER_ID]),
    CONSTRAINT [FK_ENVIRONMENT_REGISTER_APPLICATION_REGISTER_APPLICATION_REGISTER_ID] FOREIGN KEY ([APPLICATION_REGISTER_ID]) REFERENCES [APPLICATION_REGISTER] ([APPLICATION_REGISTER_ID]) ON DELETE CASCADE
);
GO


CREATE TABLE [APPLICATION_INFO] (
    [APPLICATION_INFO_ID] bigint NOT NULL IDENTITY,
    [APPLICATION_KEY] nvarchar(max) NULL,
    [DATA_MODEL_NAMESPACE] nvarchar(max) NULL,
    [SUPPORTED_INFRASTRUCTURE_VERSION] nvarchar(max) NULL,
    [TRANSPORT] nvarchar(max) NULL,
    [ENVIRONMENT_ID] uniqueidentifier NULL,
    CONSTRAINT [PK_APPLICATION_INFO] PRIMARY KEY ([APPLICATION_INFO_ID]),
    CONSTRAINT [FK_APPLICATION_INFO_ENVIRONMENT_ENVIRONMENT_ID] FOREIGN KEY ([ENVIRONMENT_ID]) REFERENCES [ENVIRONMENT] ([ENVIRONMENT_ID]) ON DELETE CASCADE
);
GO


CREATE TABLE [INFRASTRUCTURE_SERVICE] (
    [INFRASTRUCTURE_SERVICE_ID] bigint NOT NULL IDENTITY,
    [NAME] nvarchar(max) NULL,
    [VALUE] nvarchar(max) NULL,
    [ENVIRONMENT_ID] uniqueidentifier NULL,
    [ENVIRONMENT_REGISTER_ID] bigint NULL,
    CONSTRAINT [PK_INFRASTRUCTURE_SERVICE] PRIMARY KEY ([INFRASTRUCTURE_SERVICE_ID]),
    CONSTRAINT [FK_INFRASTRUCTURE_SERVICE_ENVIRONMENT_ENVIRONMENT_ID] FOREIGN KEY ([ENVIRONMENT_ID]) REFERENCES [ENVIRONMENT] ([ENVIRONMENT_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_INFRASTRUCTURE_SERVICE_ENVIRONMENT_REGISTER_ENVIRONMENT_REGISTER_ID] FOREIGN KEY ([ENVIRONMENT_REGISTER_ID]) REFERENCES [ENVIRONMENT_REGISTER] ([ENVIRONMENT_REGISTER_ID]) ON DELETE CASCADE
);
GO


CREATE TABLE [PROVISIONED_ZONE] (
    [PROVISIONED_ZONE_ID] bigint NOT NULL IDENTITY,
    [SIF_ID] nvarchar(max) NULL,
    [ENVIRONMENT_ID] uniqueidentifier NULL,
    [ENVIRONMENT_REGISTER_ID] bigint NULL,
    CONSTRAINT [PK_PROVISIONED_ZONE] PRIMARY KEY ([PROVISIONED_ZONE_ID]),
    CONSTRAINT [FK_PROVISIONED_ZONE_ENVIRONMENT_ENVIRONMENT_ID] FOREIGN KEY ([ENVIRONMENT_ID]) REFERENCES [ENVIRONMENT] ([ENVIRONMENT_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PROVISIONED_ZONE_ENVIRONMENT_REGISTER_ENVIRONMENT_REGISTER_ID] FOREIGN KEY ([ENVIRONMENT_REGISTER_ID]) REFERENCES [ENVIRONMENT_REGISTER] ([ENVIRONMENT_REGISTER_ID]) ON DELETE CASCADE
);
GO


CREATE TABLE [ZONE] (
    [ZONE_ID] bigint NOT NULL IDENTITY,
    [DESCRIPTION] nvarchar(max) NULL,
    [SIF_ID] nvarchar(max) NULL,
    [ENVIRONMENT_ID] uniqueidentifier NULL,
    [ENVIRONMENT_REGISTER_ID] bigint NULL,
    CONSTRAINT [PK_ZONE] PRIMARY KEY ([ZONE_ID]),
    CONSTRAINT [FK_ZONE_ENVIRONMENT_ENVIRONMENT_ID] FOREIGN KEY ([ENVIRONMENT_ID]) REFERENCES [ENVIRONMENT] ([ENVIRONMENT_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_ZONE_ENVIRONMENT_REGISTER_ENVIRONMENT_REGISTER_ID] FOREIGN KEY ([ENVIRONMENT_REGISTER_ID]) REFERENCES [ENVIRONMENT_REGISTER] ([ENVIRONMENT_REGISTER_ID]) ON DELETE CASCADE
);
GO


CREATE TABLE [PRODUCT_IDENTITY] (
    [PRODUCT_IDENTITY_ID] bigint NOT NULL IDENTITY,
    [ICON_URI] nvarchar(max) NULL,
    [PRODUCT_NAME] nvarchar(max) NULL,
    [PRODUCT_VERSION] nvarchar(max) NULL,
    [VENDOR_NAME] nvarchar(max) NULL,
    [ADAPTER_PRODUCT_ID] bigint NULL,
    [APPLICATION_PRODUCT_ID] bigint NULL,
    CONSTRAINT [PK_PRODUCT_IDENTITY] PRIMARY KEY ([PRODUCT_IDENTITY_ID]),
    CONSTRAINT [FK_PRODUCT_IDENTITY_APPLICATION_INFO_ADAPTER_PRODUCT_ID] FOREIGN KEY ([ADAPTER_PRODUCT_ID]) REFERENCES [APPLICATION_INFO] ([APPLICATION_INFO_ID]) ON DELETE CASCADE,
    CONSTRAINT [FK_PRODUCT_IDENTITY_APPLICATION_INFO_APPLICATION_PRODUCT_ID] FOREIGN KEY ([APPLICATION_PRODUCT_ID]) REFERENCES [APPLICATION_INFO] ([APPLICATION_INFO_ID])
);
GO


CREATE TABLE [SERVICE] (
    [SERVICE_ID] bigint NOT NULL IDENTITY,
    [CONTEXTID] nvarchar(max) NULL,
    [NAME] nvarchar(max) NULL,
    [TYPE] nvarchar(max) NULL,
    [PROVISIONED_ZONE_ID] bigint NULL,
    CONSTRAINT [PK_SERVICE] PRIMARY KEY ([SERVICE_ID]),
    CONSTRAINT [FK_SERVICE_PROVISIONED_ZONE_PROVISIONED_ZONE_ID] FOREIGN KEY ([PROVISIONED_ZONE_ID]) REFERENCES [PROVISIONED_ZONE] ([PROVISIONED_ZONE_ID]) ON DELETE CASCADE
);
GO


CREATE TABLE [PROPERTY] (
    [PROPERTY_ID] bigint NOT NULL IDENTITY,
    [NAME] nvarchar(max) NULL,
    [VALUE] nvarchar(max) NULL,
    [ZONE_ID] bigint NULL,
    CONSTRAINT [PK_PROPERTY] PRIMARY KEY ([PROPERTY_ID]),
    CONSTRAINT [FK_PROPERTY_ZONE_ZONE_ID] FOREIGN KEY ([ZONE_ID]) REFERENCES [ZONE] ([ZONE_ID]) ON DELETE CASCADE
);
GO


CREATE TABLE [RIGHT] (
    [RIGHT_ID] bigint NOT NULL IDENTITY,
    [TYPE] nvarchar(max) NULL,
    [VALUE] nvarchar(max) NULL,
    [SERVICE_ID] bigint NULL,
    CONSTRAINT [PK_RIGHT] PRIMARY KEY ([RIGHT_ID]),
    CONSTRAINT [FK_RIGHT_SERVICE_SERVICE_ID] FOREIGN KEY ([SERVICE_ID]) REFERENCES [SERVICE] ([SERVICE_ID]) ON DELETE CASCADE
);
GO


CREATE UNIQUE INDEX [IX_APPLICATION_INFO_ENVIRONMENT_ID] ON [APPLICATION_INFO] ([ENVIRONMENT_ID]) WHERE [ENVIRONMENT_ID] IS NOT NULL;
GO


CREATE INDEX [IX_ENVIRONMENT_REGISTER_APPLICATION_REGISTER_ID] ON [ENVIRONMENT_REGISTER] ([APPLICATION_REGISTER_ID]);
GO


CREATE INDEX [IX_INFRASTRUCTURE_SERVICE_ENVIRONMENT_ID] ON [INFRASTRUCTURE_SERVICE] ([ENVIRONMENT_ID]);
GO


CREATE INDEX [IX_INFRASTRUCTURE_SERVICE_ENVIRONMENT_REGISTER_ID] ON [INFRASTRUCTURE_SERVICE] ([ENVIRONMENT_REGISTER_ID]);
GO


CREATE UNIQUE INDEX [IX_PRODUCT_IDENTITY_ADAPTER_PRODUCT_ID] ON [PRODUCT_IDENTITY] ([ADAPTER_PRODUCT_ID]) WHERE [ADAPTER_PRODUCT_ID] IS NOT NULL;
GO


CREATE UNIQUE INDEX [IX_PRODUCT_IDENTITY_APPLICATION_PRODUCT_ID] ON [PRODUCT_IDENTITY] ([APPLICATION_PRODUCT_ID]) WHERE [APPLICATION_PRODUCT_ID] IS NOT NULL;
GO


CREATE INDEX [IX_PROPERTY_ZONE_ID] ON [PROPERTY] ([ZONE_ID]);
GO


CREATE INDEX [IX_PROVISIONED_ZONE_ENVIRONMENT_ID] ON [PROVISIONED_ZONE] ([ENVIRONMENT_ID]);
GO


CREATE INDEX [IX_PROVISIONED_ZONE_ENVIRONMENT_REGISTER_ID] ON [PROVISIONED_ZONE] ([ENVIRONMENT_REGISTER_ID]);
GO


CREATE INDEX [IX_RIGHT_SERVICE_ID] ON [RIGHT] ([SERVICE_ID]);
GO


CREATE INDEX [IX_SERVICE_PROVISIONED_ZONE_ID] ON [SERVICE] ([PROVISIONED_ZONE_ID]);
GO


CREATE UNIQUE INDEX [IX_ZONE_ENVIRONMENT_ID] ON [ZONE] ([ENVIRONMENT_ID]) WHERE [ENVIRONMENT_ID] IS NOT NULL;
GO


CREATE UNIQUE INDEX [IX_ZONE_ENVIRONMENT_REGISTER_ID] ON [ZONE] ([ENVIRONMENT_REGISTER_ID]) WHERE [ENVIRONMENT_REGISTER_ID] IS NOT NULL;
GO



