//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Sif.Specification.Infrastructure
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("alert", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class alertType
    {

        private string reporterField;

        private string causeField;

        private alertTypeExchange exchangeField;

        private alertTypeLevel levelField;

        private string descriptionField;

        private string messageIDField;

        private string bodyField;

        private string errorField;

        private string xpathField;

        private uint categoryField;

        private bool categoryFieldSpecified;

        private uint codeField;

        private bool codeFieldSpecified;

        private string internalField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string reporter
        {
            get
            {
                return this.reporterField;
            }
            set
            {
                this.reporterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string cause
        {
            get
            {
                return this.causeField;
            }
            set
            {
                this.causeField = value;
            }
        }

        /// <remarks/>
        public alertTypeExchange exchange
        {
            get
            {
                return this.exchangeField;
            }
            set
            {
                this.exchangeField = value;
            }
        }

        /// <remarks/>
        public alertTypeLevel level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string messageID
        {
            get
            {
                return this.messageIDField;
            }
            set
            {
                this.messageIDField = value;
            }
        }

        /// <remarks/>
        public string body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }

        /// <remarks/>
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string xpath
        {
            get
            {
                return this.xpathField;
            }
            set
            {
                this.xpathField = value;
            }
        }

        /// <remarks/>
        public uint category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categorySpecified
        {
            get
            {
                return this.categoryFieldSpecified;
            }
            set
            {
                this.categoryFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool codeSpecified
        {
            get
            {
                return this.codeFieldSpecified;
            }
            set
            {
                this.codeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string @internal
        {
            get
            {
                return this.internalField;
            }
            set
            {
                this.internalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public enum alertTypeExchange
    {

        /// <remarks/>
        REQUEST,

        /// <remarks/>
        RESPONSE,

        /// <remarks/>
        EVENT,

        /// <remarks/>
        TIMEOUT,

        /// <remarks/>
        OTHER,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public enum alertTypeLevel
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(" INFO")]
        INFO,

        /// <remarks/>
        STATECHANGE,

        /// <remarks/>
        WARNING,

        /// <remarks/>
        ERROR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("alerts", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class alertCollectionType
    {

        private alertType[] alertField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("alert")]
        public alertType[] alert
        {
            get
            {
                return this.alertField;
            }
            set
            {
                this.alertField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("codeSet", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class codeSetType
    {

        private string zoneField;

        private string versionField;

        private System.DateTime timestampField;

        private object itemField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "token")]
        public string zone
        {
            get
            {
                return this.zoneField;
            }
            set
            {
                this.zoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "token")]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codeItems", typeof(codeItemsType), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlElementAttribute("source", typeof(string), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class codeItemsType
    {

        private codeItemType codeItemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public codeItemType codeItem
        {
            get
            {
                return this.codeItemField;
            }
            set
            {
                this.codeItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class codeItemType
    {

        private string codeField;

        private string sourceField;

        private string namespaceField;

        private string valueField;

        private string descriptionField;

        private string definitionField;

        private aliasType[] aliasesField;

        private codeItemTypeAction actionField;

        private System.DateTime timestampField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "token")]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI", IsNullable = true)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI", IsNullable = true)]
        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "token", IsNullable = true)]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "normalizedString")]
        public string definition
        {
            get
            {
                return this.definitionField;
            }
            set
            {
                this.definitionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("alias", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public aliasType[] aliases
        {
            get
            {
                return this.aliasesField;
            }
            set
            {
                this.aliasesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public codeItemTypeAction action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class aliasType
    {

        private codeType codeField;

        private string sourceField;

        private string namespaceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public codeType code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI", IsNullable = true)]
        public string source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI", IsNullable = true)]
        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class codeType
    {

        private bool oldField;

        private bool officialField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool old
        {
            get
            {
                return this.oldField;
            }
            set
            {
                this.oldField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool official
        {
            get
            {
                return this.officialField;
            }
            set
            {
                this.officialField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "token")]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public enum codeItemTypeAction
    {

        /// <remarks/>
        ADD,

        /// <remarks/>
        CHANGE,

        /// <remarks/>
        DEPRECATED,

        /// <remarks/>
        DELETE,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("codeSets", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class codeSetCollectionType
    {

        private codeSetType[] codeSetField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codeSet")]
        public codeSetType[] codeSet
        {
            get
            {
                return this.codeSetField;
            }
            set
            {
                this.codeSetField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("createResponse", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class createResponseType
    {

        private createType[] createsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("create", IsNullable = false)]
        public createType[] creates
        {
            get
            {
                return this.createsField;
            }
            set
            {
                this.createsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class createType
    {

        private errorType errorField;

        private string idField;

        private string statusCodeField;

        /// <remarks/>
        public errorType error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("error", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class errorType
    {

        private uint codeField;

        private string scopeField;

        private string messageField;

        private string descriptionField;

        private string idField;

        /// <remarks/>
        public uint code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string scope
        {
            get
            {
                return this.scopeField;
            }
            set
            {
                this.scopeField = value;
            }
        }

        /// <remarks/>
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("deleteRequest", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class deleteRequestType
    {

        private deleteIdType[] deletesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("delete", IsNullable = false)]
        public deleteIdType[] deletes
        {
            get
            {
                return this.deletesField;
            }
            set
            {
                this.deletesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class deleteIdType
    {

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("deleteResponse", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class deleteResponseType
    {

        private deleteStatus[] deletesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("delete", IsNullable = false)]
        public deleteStatus[] deletes
        {
            get
            {
                return this.deletesField;
            }
            set
            {
                this.deletesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class deleteStatus
    {

        private errorType errorField;

        private string idField;

        private string statusCodeField;

        /// <remarks/>
        public errorType error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("environment", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class environmentType
    {

        private string sessionTokenField;

        private string solutionIdField;

        private zoneType defaultZoneField;

        private string authenticationMethodField;

        private string instanceIdField;

        private string userTokenField;

        private string consumerNameField;

        private applicationInfoType applicationInfoField;

        private propertyType[] infrastructureServicesField;

        private provisionedZoneType[] provisionedZonesField;

        private environmentTypeType typeField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string sessionToken
        {
            get
            {
                return this.sessionTokenField;
            }
            set
            {
                this.sessionTokenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string solutionId
        {
            get
            {
                return this.solutionIdField;
            }
            set
            {
                this.solutionIdField = value;
            }
        }

        /// <remarks/>
        public zoneType defaultZone
        {
            get
            {
                return this.defaultZoneField;
            }
            set
            {
                this.defaultZoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string authenticationMethod
        {
            get
            {
                return this.authenticationMethodField;
            }
            set
            {
                this.authenticationMethodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string instanceId
        {
            get
            {
                return this.instanceIdField;
            }
            set
            {
                this.instanceIdField = value;
            }
        }

        /// <remarks/>
        public string userToken
        {
            get
            {
                return this.userTokenField;
            }
            set
            {
                this.userTokenField = value;
            }
        }

        /// <remarks/>
        public string consumerName
        {
            get
            {
                return this.consumerNameField;
            }
            set
            {
                this.consumerNameField = value;
            }
        }

        /// <remarks/>
        public applicationInfoType applicationInfo
        {
            get
            {
                return this.applicationInfoField;
            }
            set
            {
                this.applicationInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("infrastructureService", IsNullable = false)]
        public propertyType[] infrastructureServices
        {
            get
            {
                return this.infrastructureServicesField;
            }
            set
            {
                this.infrastructureServicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("provisionedZone", IsNullable = false)]
        public provisionedZoneType[] provisionedZones
        {
            get
            {
                return this.provisionedZonesField;
            }
            set
            {
                this.provisionedZonesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public environmentTypeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("zone", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class zoneType
    {

        private string descriptionField;

        private propertiesType propertiesField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public propertiesType properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class propertiesType
    {

        private propertyType propertyField;

        /// <remarks/>
        public propertyType property
        {
            get
            {
                return this.propertyField;
            }
            set
            {
                this.propertyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class propertyType
    {

        private string nameField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class applicationInfoType
    {

        private string applicationKeyField;

        private string supportedInfrastructureVersionField;

        private string supportedDataModelField;

        private string supportedDataModelVersionField;

        private string transportField;

        private productIdentityType applicationProductField;

        private productIdentityType adapterProductField;

        /// <remarks/>
        public string applicationKey
        {
            get
            {
                return this.applicationKeyField;
            }
            set
            {
                this.applicationKeyField = value;
            }
        }

        /// <remarks/>
        public string supportedInfrastructureVersion
        {
            get
            {
                return this.supportedInfrastructureVersionField;
            }
            set
            {
                this.supportedInfrastructureVersionField = value;
            }
        }

        /// <remarks/>
        public string supportedDataModel
        {
            get
            {
                return this.supportedDataModelField;
            }
            set
            {
                this.supportedDataModelField = value;
            }
        }

        /// <remarks/>
        public string supportedDataModelVersion
        {
            get
            {
                return this.supportedDataModelVersionField;
            }
            set
            {
                this.supportedDataModelVersionField = value;
            }
        }

        /// <remarks/>
        public string transport
        {
            get
            {
                return this.transportField;
            }
            set
            {
                this.transportField = value;
            }
        }

        /// <remarks/>
        public productIdentityType applicationProduct
        {
            get
            {
                return this.applicationProductField;
            }
            set
            {
                this.applicationProductField = value;
            }
        }

        /// <remarks/>
        public productIdentityType adapterProduct
        {
            get
            {
                return this.adapterProductField;
            }
            set
            {
                this.adapterProductField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class productIdentityType
    {

        private string vendorNameField;

        private string productNameField;

        private string productVersionField;

        private string iconURIField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string vendorName
        {
            get
            {
                return this.vendorNameField;
            }
            set
            {
                this.vendorNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string productName
        {
            get
            {
                return this.productNameField;
            }
            set
            {
                this.productNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string productVersion
        {
            get
            {
                return this.productVersionField;
            }
            set
            {
                this.productVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string iconURI
        {
            get
            {
                return this.iconURIField;
            }
            set
            {
                this.iconURIField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class provisionedZoneType
    {

        private serviceType[] servicesField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("service", IsNullable = false)]
        public serviceType[] services
        {
            get
            {
                return this.servicesField;
            }
            set
            {
                this.servicesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class serviceType
    {

        private rightType[] rightsField;

        private string nameField;

        private string contextIdField;

        private string typeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("right", IsNullable = false)]
        public rightType[] rights
        {
            get
            {
                return this.rightsField;
            }
            set
            {
                this.rightsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string contextId
        {
            get
            {
                return this.contextIdField;
            }
            set
            {
                this.contextIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class rightType
    {

        private string typeField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType = "token")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public enum environmentTypeType
    {

        /// <remarks/>
        DIRECT,

        /// <remarks/>
        BROKERED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("namespace", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class namespaceType
    {

        private string zoneField;

        private string uriField;

        private string urlField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string zone
        {
            get
            {
                return this.zoneField;
            }
            set
            {
                this.zoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string uri
        {
            get
            {
                return this.uriField;
            }
            set
            {
                this.uriField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("namespaces", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class namespaceCollectionType
    {

        private namespaceType[] namespaceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("namespace")]
        public namespaceType[] @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("provider", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class providerType
    {

        private string serviceTypeField;

        private string serviceNameField;

        private contextType contextField;

        private querySupportType querySupportField;

        private protocolType endPointField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string serviceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }

        /// <remarks/>
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }

        /// <remarks/>
        public contextType context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }

        /// <remarks/>
        public querySupportType querySupport
        {
            get
            {
                return this.querySupportField;
            }
            set
            {
                this.querySupportField = value;
            }
        }

        /// <remarks/>
        public protocolType endPoint
        {
            get
            {
                return this.endPointField;
            }
            set
            {
                this.endPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class contextType
    {

        private string contextNameField;

        private string zoneIDField;

        private string providernameField;

        private string dataModelNamespaceField;

        /// <remarks/>
        public string contextName
        {
            get
            {
                return this.contextNameField;
            }
            set
            {
                this.contextNameField = value;
            }
        }

        /// <remarks/>
        public string zoneID
        {
            get
            {
                return this.zoneIDField;
            }
            set
            {
                this.zoneIDField = value;
            }
        }

        /// <remarks/>
        public string providername
        {
            get
            {
                return this.providernameField;
            }
            set
            {
                this.providernameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string dataModelNamespace
        {
            get
            {
                return this.dataModelNamespaceField;
            }
            set
            {
                this.dataModelNamespaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class querySupportType
    {

        private bool singularField;

        private bool formulaField;

        private bool pagedField;

        private uint maxPageSizeField;

        private string applicationProductField;

        private productIdentityType adapterProductField;

        /// <remarks/>
        public bool singular
        {
            get
            {
                return this.singularField;
            }
            set
            {
                this.singularField = value;
            }
        }

        /// <remarks/>
        public bool formula
        {
            get
            {
                return this.formulaField;
            }
            set
            {
                this.formulaField = value;
            }
        }

        /// <remarks/>
        public bool paged
        {
            get
            {
                return this.pagedField;
            }
            set
            {
                this.pagedField = value;
            }
        }

        /// <remarks/>
        public uint maxPageSize
        {
            get
            {
                return this.maxPageSizeField;
            }
            set
            {
                this.maxPageSizeField = value;
            }
        }

        /// <remarks/>
        public string applicationProduct
        {
            get
            {
                return this.applicationProductField;
            }
            set
            {
                this.applicationProductField = value;
            }
        }

        /// <remarks/>
        public productIdentityType adapterProduct
        {
            get
            {
                return this.adapterProductField;
            }
            set
            {
                this.adapterProductField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class protocolType
    {

        private string locationField;

        private propertiesType[] propertiesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties")]
        public propertiesType[] properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("providers", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class providerCollectionType
    {

        private providerType[] providerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("provider")]
        public providerType[] provider
        {
            get
            {
                return this.providerField;
            }
            set
            {
                this.providerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("provisionRequest", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class provisionRequestType
    {

        private provisionedZoneType[] provisionedZonesField;

        private provisionRequestTypeCompletionStatus completionStatusField;

        private bool completionStatusFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("provisionedZone", IsNullable = false)]
        public provisionedZoneType[] provisionedZones
        {
            get
            {
                return this.provisionedZonesField;
            }
            set
            {
                this.provisionedZonesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public provisionRequestTypeCompletionStatus completionStatus
        {
            get
            {
                return this.completionStatusField;
            }
            set
            {
                this.completionStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completionStatusSpecified
        {
            get
            {
                return this.completionStatusFieldSpecified;
            }
            set
            {
                this.completionStatusFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public enum provisionRequestTypeCompletionStatus
    {

        /// <remarks/>
        ACCEPTED,

        /// <remarks/>
        MIXED,

        /// <remarks/>
        REJECTED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("queue", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class queueType
    {

        private queueTypePolling pollingField;

        private bool pollingFieldSpecified;

        private string ownerIdField;

        private string nameField;

        private string queueURIField;

        private uint idleTimeoutField;

        private uint minWaitTimeField;

        private bool minWaitTimeFieldSpecified;

        private uint maxConcurrentConnectionsField;

        private bool maxConcurrentConnectionsFieldSpecified;

        private System.DateTime createdField;

        private System.DateTime lastAccessedField;

        private System.DateTime lastModifiedField;

        private uint messageCountField;

        private string idField;

        /// <remarks/>
        public queueTypePolling polling
        {
            get
            {
                return this.pollingField;
            }
            set
            {
                this.pollingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pollingSpecified
        {
            get
            {
                return this.pollingFieldSpecified;
            }
            set
            {
                this.pollingFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string ownerId
        {
            get
            {
                return this.ownerIdField;
            }
            set
            {
                this.ownerIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "anyURI")]
        public string queueURI
        {
            get
            {
                return this.queueURIField;
            }
            set
            {
                this.queueURIField = value;
            }
        }

        /// <remarks/>
        public uint idleTimeout
        {
            get
            {
                return this.idleTimeoutField;
            }
            set
            {
                this.idleTimeoutField = value;
            }
        }

        /// <remarks/>
        public uint minWaitTime
        {
            get
            {
                return this.minWaitTimeField;
            }
            set
            {
                this.minWaitTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minWaitTimeSpecified
        {
            get
            {
                return this.minWaitTimeFieldSpecified;
            }
            set
            {
                this.minWaitTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public uint maxConcurrentConnections
        {
            get
            {
                return this.maxConcurrentConnectionsField;
            }
            set
            {
                this.maxConcurrentConnectionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxConcurrentConnectionsSpecified
        {
            get
            {
                return this.maxConcurrentConnectionsFieldSpecified;
            }
            set
            {
                this.maxConcurrentConnectionsFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime lastAccessed
        {
            get
            {
                return this.lastAccessedField;
            }
            set
            {
                this.lastAccessedField = value;
            }
        }

        /// <remarks/>
        public System.DateTime lastModified
        {
            get
            {
                return this.lastModifiedField;
            }
            set
            {
                this.lastModifiedField = value;
            }
        }

        /// <remarks/>
        public uint messageCount
        {
            get
            {
                return this.messageCountField;
            }
            set
            {
                this.messageCountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public enum queueTypePolling
    {

        /// <remarks/>
        IMMEDIATE,

        /// <remarks/>
        LONG,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("queues", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class queueCollectionType
    {

        private queueType[] queueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("queue")]
        public queueType[] queue
        {
            get
            {
                return this.queueField;
            }
            set
            {
                this.queueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("subscription", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class subscriptionType
    {

        private string zoneIdField;

        private string contextIdField;

        private string serviceTypeField;

        private string serviceNameField;

        private string queueIdField;

        private string idField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string zoneId
        {
            get
            {
                return this.zoneIdField;
            }
            set
            {
                this.zoneIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string contextId
        {
            get
            {
                return this.contextIdField;
            }
            set
            {
                this.contextIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string serviceType
        {
            get
            {
                return this.serviceTypeField;
            }
            set
            {
                this.serviceTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string queueId
        {
            get
            {
                return this.queueIdField;
            }
            set
            {
                this.queueIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("subscriptions", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class subscriptionCollectionType
    {

        private subscriptionType[] subscriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subscription")]
        public subscriptionType[] subscription
        {
            get
            {
                return this.subscriptionField;
            }
            set
            {
                this.subscriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("updateResponse", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class updateResponseType
    {

        private updateType[] updatesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("update", IsNullable = false)]
        public updateType[] updates
        {
            get
            {
                return this.updatesField;
            }
            set
            {
                this.updatesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class updateType
    {

        private errorType errorField;

        private string idField;

        private string statusCodeField;

        /// <remarks/>
        public errorType error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string statusCode
        {
            get
            {
                return this.statusCodeField;
            }
            set
            {
                this.statusCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("xquery", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class xqueryType
    {

        private xqueryTypeType typeField;

        private xqueryTypeStatus statusField;

        private string qualifierField;

        private string descriptionField;

        private string scriptField;

        private xpathType[] includeField;

        private string idField;

        /// <remarks/>
        public xqueryTypeType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public xqueryTypeStatus status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string qualifier
        {
            get
            {
                return this.qualifierField;
            }
            set
            {
                this.qualifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "normalizedString")]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string script
        {
            get
            {
                return this.scriptField;
            }
            set
            {
                this.scriptField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("xpath", IsNullable = false)]
        public xpathType[] include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public enum xqueryTypeType
    {

        /// <remarks/>
        FORMULA,

        /// <remarks/>
        EXTENDED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public enum xqueryTypeStatus
    {

        /// <remarks/>
        PENDING,

        /// <remarks/>
        APPROVED,

        /// <remarks/>
        DISALLOWED,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class xpathType
    {

        private string pathField;

        private namespaceQualifiersType namespacesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token")]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        public namespaceQualifiersType namespaces
        {
            get
            {
                return this.namespacesField;
            }
            set
            {
                this.namespacesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class namespaceQualifiersType
    {

        private namespaceQualifierType namespaceField;

        /// <remarks/>
        public namespaceQualifierType @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    public partial class namespaceQualifierType
    {

        private string prefixField;

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", IsNullable = true)]
        public string prefix
        {
            get
            {
                return this.prefixField;
            }
            set
            {
                this.prefixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("regularExpression", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("startsWith", typeof(string), DataType = "token")]
        [System.Xml.Serialization.XmlElementAttribute("static", typeof(string), DataType = "anyURI")]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        regularExpression,

        /// <remarks/>
        startsWith,

        /// <remarks/>
        @static,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("xquerys", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class xqueryCollectionType
    {

        private xqueryType[] xqueryField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("xquery")]
        public xqueryType[] xquery
        {
            get
            {
                return this.xqueryField;
            }
            set
            {
                this.xqueryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.sifassociation.org/infrastructure/3.0")]
    [System.Xml.Serialization.XmlRootAttribute("zones", Namespace = "http://www.sifassociation.org/infrastructure/3.0", IsNullable = false)]
    public partial class zoneCollectionType
    {

        private zoneType[] zoneField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("zone")]
        public zoneType[] zone
        {
            get
            {
                return this.zoneField;
            }
            set
            {
                this.zoneField = value;
            }
        }
    }
}
