CREATE TABLE "SERVICE" (
    "SERVICE_ID" INTEGER NOT NULL CONSTRAINT "PK_SERVICE" PRIMARY KEY AUTOINCREMENT,
    "CONTEXTID" TEXT NULL,
    "NAME" TEXT NULL,
    "TYPE" TEXT NULL
);


CREATE TABLE "RIGHT" (
    "RIGHT_ID" INTEGER NOT NULL CONSTRAINT "PK_RIGHT" PRIMARY KEY AUTOINCREMENT,
    "TYPE" TEXT NULL,
    "VALUE" TEXT NULL,
    "SERVICE_ID" INTEGER NOT NULL,
    CONSTRAINT "FK_RIGHT_SERVICE_SERVICE_ID" FOREIGN KEY ("SERVICE_ID") REFERENCES "SERVICE" ("SERVICE_ID") ON DELETE CASCADE
);


CREATE INDEX "IX_RIGHT_SERVICE_ID" ON "RIGHT" ("SERVICE_ID");



