CREATE TABLE "INFRASTRUCTURE_SERVICE" (
    "INFRASTRUCTURE_SERVICE_ID" INTEGER NOT NULL CONSTRAINT "PK_INFRASTRUCTURE_SERVICE" PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT NULL,
    "VALUE" TEXT NULL
);


CREATE TABLE "PRODUCT_IDENTITY" (
    "PRODUCT_IDENTITY_ID" INTEGER NOT NULL CONSTRAINT "PK_PRODUCT_IDENTITY" PRIMARY KEY AUTOINCREMENT,
    "ICON_URI" TEXT NULL,
    "PRODUCT_NAME" TEXT NULL,
    "PRODUCT_VERSION" TEXT NULL,
    "VENDOR_NAME" TEXT NULL
);


CREATE TABLE "PROVISIONED_ZONE" (
    "PROVISIONED_ZONE_ID" INTEGER NOT NULL CONSTRAINT "PK_PROVISIONED_ZONE" PRIMARY KEY AUTOINCREMENT,
    "SIF_ID" TEXT NULL
);


CREATE TABLE "APPLICATION_INFO" (
    "APPLICATION_INFO_ID" INTEGER NOT NULL CONSTRAINT "PK_APPLICATION_INFO" PRIMARY KEY AUTOINCREMENT,
    "ADAPTER_PRODUCT_ID" INTEGER NULL,
    "APPLICATION_KEY" TEXT NULL,
    "APPLICATION_PRODUCT_ID" INTEGER NULL,
    "DATA_MODEL_NAMESPACE" TEXT NULL,
    "SUPPORTED_INFRASTRUCTURE_VERSION" TEXT NULL,
    "TRANSPORT" TEXT NULL,
    CONSTRAINT "FK_APPLICATION_INFO_PRODUCT_IDENTITY_ADAPTER_PRODUCT_ID" FOREIGN KEY ("ADAPTER_PRODUCT_ID") REFERENCES "PRODUCT_IDENTITY" ("PRODUCT_IDENTITY_ID"),
    CONSTRAINT "FK_APPLICATION_INFO_PRODUCT_IDENTITY_APPLICATION_PRODUCT_ID" FOREIGN KEY ("APPLICATION_PRODUCT_ID") REFERENCES "PRODUCT_IDENTITY" ("PRODUCT_IDENTITY_ID")
);


CREATE TABLE "SERVICE" (
    "SERVICE_ID" INTEGER NOT NULL CONSTRAINT "PK_SERVICE" PRIMARY KEY AUTOINCREMENT,
    "CONTEXTID" TEXT NULL,
    "NAME" TEXT NULL,
    "TYPE" TEXT NULL,
    "PROVISIONED_ZONE_ID" INTEGER NULL,
    CONSTRAINT "FK_SERVICE_PROVISIONED_ZONE_PROVISIONED_ZONE_ID" FOREIGN KEY ("PROVISIONED_ZONE_ID") REFERENCES "PROVISIONED_ZONE" ("PROVISIONED_ZONE_ID")
);


CREATE TABLE "RIGHT" (
    "RIGHT_ID" INTEGER NOT NULL CONSTRAINT "PK_RIGHT" PRIMARY KEY AUTOINCREMENT,
    "TYPE" TEXT NULL,
    "VALUE" TEXT NULL,
    "SERVICE_ID" INTEGER NULL,
    CONSTRAINT "FK_RIGHT_SERVICE_SERVICE_ID" FOREIGN KEY ("SERVICE_ID") REFERENCES "SERVICE" ("SERVICE_ID")
);


CREATE INDEX "IX_APPLICATION_INFO_ADAPTER_PRODUCT_ID" ON "APPLICATION_INFO" ("ADAPTER_PRODUCT_ID");


CREATE INDEX "IX_APPLICATION_INFO_APPLICATION_PRODUCT_ID" ON "APPLICATION_INFO" ("APPLICATION_PRODUCT_ID");


CREATE INDEX "IX_RIGHT_SERVICE_ID" ON "RIGHT" ("SERVICE_ID");


CREATE INDEX "IX_SERVICE_PROVISIONED_ZONE_ID" ON "SERVICE" ("PROVISIONED_ZONE_ID");



