CREATE TABLE "INFRASTRUCTURE_SERVICE" (
    "INFRASTRUCTURE_SERVICE_ID" INTEGER NOT NULL CONSTRAINT "PK_INFRASTRUCTURE_SERVICE" PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT NULL,
    "VALUE" TEXT NULL
);


CREATE TABLE "PROVISIONED_ZONE" (
    "PROVISIONED_ZONE_ID" INTEGER NOT NULL CONSTRAINT "PK_PROVISIONED_ZONE" PRIMARY KEY AUTOINCREMENT,
    "SIF_ID" TEXT NULL
);


CREATE TABLE "SERVICE" (
    "SERVICE_ID" INTEGER NOT NULL CONSTRAINT "PK_SERVICE" PRIMARY KEY AUTOINCREMENT,
    "CONTEXTID" TEXT NULL,
    "NAME" TEXT NULL,
    "TYPE" TEXT NULL,
    "PROVISIONED_ZONE_ID" INTEGER NULL,
    CONSTRAINT "FK_SERVICE_PROVISIONED_ZONE_PROVISIONED_ZONE_ID" FOREIGN KEY ("PROVISIONED_ZONE_ID") REFERENCES "PROVISIONED_ZONE" ("PROVISIONED_ZONE_ID")
);


CREATE TABLE "RIGHT" (
    "RIGHT_ID" INTEGER NOT NULL CONSTRAINT "PK_RIGHT" PRIMARY KEY AUTOINCREMENT,
    "TYPE" TEXT NULL,
    "VALUE" TEXT NULL,
    "SERVICE_ID" INTEGER NULL,
    CONSTRAINT "FK_RIGHT_SERVICE_SERVICE_ID" FOREIGN KEY ("SERVICE_ID") REFERENCES "SERVICE" ("SERVICE_ID")
);


CREATE INDEX "IX_RIGHT_SERVICE_ID" ON "RIGHT" ("SERVICE_ID");


CREATE INDEX "IX_SERVICE_PROVISIONED_ZONE_ID" ON "SERVICE" ("PROVISIONED_ZONE_ID");



